name: R-ODAF
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - anaconda-clean
  - rsem
  - fastp
  - star
  - multiqc=1.12
  - snakemake
  - pandoc
  - libstdcxx-ng
  # R CRAN
  - r-devtools
  - r-here
  - r-curl
  - r-sessioninfo
  - r-BiocManager
  - r-tidyverse
  - r-yaml
  - r-plotly
  - r-data.table
  - r-cluster
  - r-cairo=1.5
  - r-sfsmisc
  - r-fields
  - r-heatmap3
  - r-foreach
  - r-doParallel
  - r-UpSetR
  - r-GGally
  - r-pheatmap
  - r-kableExtra
  - r-dendextend
  - r-dendsort
  - r-rrcov
  - r-vtree
  - r-knitr
  - r-magrittr
  - r-DT
  - r-lattice
  - r-tidytext
  - r-openxlsx
  - r-RColorBrewer
  - r-viridis
  - r-sessioninfo
  - r-gtools
  - r-ggridges
  - r-remotes
  - r-ashr
  - r-rvcheck=0.1.8
  # Install these via different mechanism.
  #- r-crosstalk
  #- r-crosstool
  #- r-cellWise
  # R Bioconductor
  - bioconductor-go.db=3.13
  - bioconductor-genomeinfodb=1.28
  - bioconductor-genomeinfodbdata=1.2.6
  - bioconductor-QuasR
  - bioconductor-rtracklayer
  - bioconductor-GenomicFeatures
  - bioconductor-clusterProfiler
  - bioconductor-edgeR
  - bioconductor-DESeq2
  - bioconductor-ComplexHeatmap
  - bioconductor-limma
  - bioconductor-enrichplot
  - bioconductor-org.hs.eg.db
